### ISSUE TITLE
Would you mind making the online content of iframes available offline?

### ISSUE THREAD

**Issue by RaebingZhong** [xmindltd/xmind-embed-viewer#1]
Since some contents of this viewer are loaded through iframes with https. This module can only be used in online web development, especially the iframe content from 'https://www.xmind.net/embed-viewer/'. Could you please let us access and use this embed-viewer offline one day?

**Comment by danielsss** [comment]
The main rendering engine isn't an open-source library. In other hand, It depends on our company's decision. 

thanks for your suggestion.
