### ISSUE TITLE
Can it be used offline?

### ISSUE THREAD

**Issue by willgates041** [xmindltd/xmind-embed-viewer#10]
I tested this project and had a great experience, but I found that the final rendering is based on an online address. 
Considering possible issues with speed and stability, I would like to inquire if it is possible to copy the code corresponding to the address and use it offline.

**Comment by dyingsunlight** [comment]
Regrettably, that's not possible because the core rendering engine is not open-source. The purpose of this library is to leverage some interfaces exposed by the online XMind Share website to load any user files. This way, we can better utilize the interface to customize the display content without needing to upload the files to the XMind Share server.

**Comment by alfem** [comment]
I supposse I can not use this viewer in an Intranet website behind firewalls. Am I right?

**Comment by dyingsunlight** [comment]
> I supposse I can not use this viewer in an Intranet website behind firewalls. Am I right?

Firstly, you should check your Content Security Policy (CSP). If your website restricts the embedding of iframes from certain sources, it indeed won't load or function unless you allow xmind.app as a source for iframe loading.

Secondly, once you've confirmed that the loading of the iframe hasn't been blocked by the browser, if you're still unable to load the file, you should check whether your file is being correctly loaded and provided. This includes checking the file's CORS policy and whether it's a valid file format, etc.

If you're still encountering issues after going through the above checks, please provide the specific error details to us to slove the problem.

**Comment by alfem** [comment]
I think I must clarify the 'Intranet' concept. Our users are in a corporate private network. Our intranet servers are in that network and users can browse webpages served by them. But neither users nor servers can access the Internet. If a frame, library or anything is not pre-downloadable and installed in our intranet servers by our tech team, then it just will not work.

**Comment by dyingsunlight** [comment]
> I think I must clarify the 'Intranet' concept. Our users are in a corporate private network. Our intranet servers are in that network and users can browse webpages served by them. But neither users nor servers can access the Internet. If a frame, library or anything is not pre-downloadable and installed in our intranet servers by our tech team, then it just will not work.

You are right, the embed viewer does not work without public network access, such as under a DMZ network etc. This is because it loads HTML and scripts from xmind.app.
