### ISSUE TITLE
不支持内网环境

### ISSUE THREAD

**Issue by yukun405** [xmindltd/xmind-embed-viewer#14]
内网环境预览失败

**Comment by dyingsunlight** [comment]
你好，的确是不支持隔离的内网环境的。[xmind-embed-viewer](https://github.com/xmindltd/xmind-embed-viewer) 是使用 [xmind share](https://xmind.app/share) 暴露的 API 来加载用户自定义文件，所以必须要能够访问 xmind.app 的域名才能够正常使用。
