### ISSUE TITLE
如何导出思维导图图片

### ISSUE THREAD

**Issue by Liushuxin83** [xmindltd/xmind-embed-viewer#15]
目前我在web端使用该库展示了xmind文件。但是由于iframe跨域的存在，我无法生成思维导图的图片。有什么好的办法可以生成xmind思维导图的图片吗?

**Comment by dyingsunlight** [comment]
你好，我们目前暂时没有计划去支持这个特性呢，并且这似乎不应该是一个查看器角色应该承载的功能。

总之，未来我们讨论功能规划时候，我会试着提出看能否支持的。
