### ISSUE TITLE
xmind-embed-viewer如何实现添加更多的下拉选项

### ISSUE THREAD

**Issue by okwen5566** [xmindltd/xmind-embed-viewer#4]
我在https://xmind.app/mindmap/gods.xmind/EDYvaT/?from=gallery，看到有这种下拉选择，可以选择下载文件，选择网页打开本地的xmind，请问在xmind-embed-viewer中实现
![image](https://user-images.githubusercontent.com/14171056/232373655-f6a832ef-04be-461f-9543-b51af11e43b5.png)

**Comment by dyingsunlight** [comment]
`xmind-embed-viewer` 的定位是 xmind 文件查看器，只提供的嵌入到第三方网站的展示功能，下载文件等操作应当由第三方网站自身提供。

类似功能的实现方式
- 调用客户端可以参考 `url scheme` ：
```
xmind://editor/open-url?url=<encodeURIComponent 后的文件地址>&filename=<encodeURIComponent 后的文件名>
```
- 下载文件可以使用类似 [file-saver](https://www.npmjs.com/package/file-saver) 等库进行操作

**Comment by okwen5566** [comment]
好的，谢谢您提供的方案；
我更想知道的是，目前xmind-embed-viewer的选择框就只有这些
![image](https://user-images.githubusercontent.com/14171056/232643386-9cceb277-a28c-4c06-b678-e606c1f04b68.png)

就是有没有什么配置或者方法可以在图上拓展添加这个下拉选项的组件，谢谢。
![image](https://user-images.githubusercontent.com/14171056/232643558-12453a23-d007-4792-97d2-6251963dd473.png)

**Comment by okwen5566** [comment]
> `xmind-embed-viewer` 的定位是 xmind 文件查看器，只提供的嵌入到第三方网站的展示功能，下载文件等操作应当由第三方网站自身提供。
> 
> 类似功能的实现方式
> 
> * 调用客户端可以参考 `url scheme` ：
> 
> ```
> xmind://editor/open-url?url=<encodeURIComponent 后的文件地址>&filename=<encodeURIComponent 后的文件名>
> ```
> 
> * 下载文件可以使用类似 [file-saver](https://www.npmjs.com/package/file-saver) 等库进行操作

@dyingsunlight 好的，谢谢您提供的方案；
我更想知道的是，目前xmind-embed-viewer的操作栏就只有这些
![image](https://user-images.githubusercontent.com/14171056/232644417-a14cf60c-b875-4220-bc7f-fab32e68b4db.png)

就是有没有什么配置或者方法可以在图上的操作栏拓展添加这个下拉选项的组件，谢谢。
![image](https://user-images.githubusercontent.com/14171056/232644432-6525f482-e01a-4c5a-b2b7-2798b60f26a7.png)

**Comment by dyingsunlight** [comment]
这个组件是不支持拓展的

**Comment by okwen5566** [comment]
@dyingsunlight ![image](https://user-images.githubusercontent.com/14171056/232695848-c534070c-9ba3-4d21-94a6-0240798ee6f9.png)
我在访问这个的时候https://xmind.app/mindmap/data-structure/LHug4M/?from=gallery#，他可以出现上图的选项
但是我根据你提供的url scheme调用方法，他没有出现这个选项
![image](https://user-images.githubusercontent.com/14171056/232696490-5e1ff7b4-c400-4b18-bce1-034f6c4b959c.png)
我使用的url scheme：xmind-zen://editor/open-url?url=https://lw-supply.oss-cn-shenzhen.aliyuncs.com/mytest/hello.xmind
想请教一下要出现“始终允许在关联应用中打开此类链接”这个选项要怎么弄，谢谢

**Comment by dyingsunlight** [comment]
这个是浏览器的安全策略限制，“始终允许在关联应用中打开此类链接” 的勾选框只在网站 https 有效时候会出现的
