### ISSUE TITLE
ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by voezy** [xmindltd/xmind-embed-viewer#5]
I found this output in console when i try to use xmind-embed-viewer(npm version 1.1.0), and this is the same in the online demo website. Am i did something wrong?

<img width="649" alt="截屏2023-05-25 上午12 03 19" src="https://github.com/xmindltd/xmind-embed-viewer/assets/20068385/362636f7-39e3-4e02-8b31-ecb66d5cb7c4">

**Comment by dyingsunlight** [comment]
Thank you for reporting this issue. It seems that our website indeed has some problems with the embed-viewer. We will work on fixing these issues as soon as possible.

**Comment by dyingsunlight** [comment]
The problem has been fixed now.
