### ISSUE TITLE
由于访问慢，可以加一个代理吗

### ISSUE THREAD

**Issue by teenth** [xmindltd/xmind-embed-viewer#8]
const iframeController = new IframeController(el, `https://www.xmind.app/embed-viewer${ isPitchModeDisa

修改成
 const iframeController = new IframeController(el, `${prefix}/embed-viewer${ isPitchModeDisa

**Comment by dyingsunlight** [comment]
你好，虽然似乎是可行的，但这种方法还是有点粗暴了。主要提醒了我国内用户可以用 `xmind.cn` 的服务器源来加速，所以我调整了下代码，额外支持了 `region`: 'cn' 来初始化 viewer 。
### 用法
```typescript
const viewer = new XMindEmbedViewer({
  el: '#container-or-iframe-selector',
  // 如果在中国大陆境内速度慢，可以添加的参数 `region: 'cn'` 改为使用 xmind.cn 的图库作为依赖。
  region: 'cn'
})
```

### 为什么不直接支持自定义前缀？
大概概括一下：
- 使用比较复杂。支持除了修改 IframeController 外， IframeEventChannelController 的广播域名限制也要改为代理地址
- 需求比较少见。代理这种方式从长期来看普遍不太稳定，并且不是每个用户都会有自己的代理
- 自定义前缀涉及影响范围大。容易导致以后失去调整挪腾的空间

---

总之可以先尝试一下新的参数看看吧

**Comment by oqq5518** [comment]
请问这个是什么意思呢？
<img width="635" alt="CleanShot 2023-07-31 at 11 34 52@2x" src="https://github.com/xmindltd/xmind-embed-viewer/assets/4516065/5f215e75-c2ba-44b1-9b79-0d115730f64d">

**Comment by oqq5518** [comment]
我加载这个组件，发现它也是好慢

**Comment by dyingsunlight** [comment]
> 我加载这个组件，发现它也是好慢

首先，请按照以下流程排查问题：
- 确认安装的 `xmind-embed-viewer` 版本是 `1.2.0`  或者是更高。
- 确认初始化参数中有添加 `region: 'cn'`，比如：
```typescript
const viewer = new XMindEmbedViewer({
  el: '#container-or-iframe-selector',
  region: 'cn'
})
```

如果上述操作无法解决问题，为了进一步排查原因，请打开  [demo](https://xmindltd.github.io/xmind-embed-viewer/) 并使用页面内 “切换到国内源” 的选项检查速度是否有变快。
- 假如速度变快了，那么一定是用法有问题，你可以参考 [demo](https://github.com/xmindltd/xmind-embed-viewer/blob/423627eb87f24c72aa68f20e961c9f12d4e7d021/public/index.html#L51) 重新调整你的代码
- 假如仍然加载慢，很可能是网络运营商线路的问题，awschina cloudfront cdn 节点可能没能覆盖到你的区域或者运营商，这点我们没有办法解决。

**Comment by oqq5518** [comment]
初始化参数 region: 'cn'
我加载的 xmind 是放在阿里云服务器的，加不加这个参数，有区别吗？

**Comment by dyingsunlight** [comment]
和文件位置无关， `region: 'cn'` 只影响 `ifram` 页面的加载速度。

**Comment by teenth** [comment]
> > 我加载这个组件，发现它也是好慢
> 
> 首先，请按照以下流程排查问题：
> 
> * 确认安装的 `xmind-embed-viewer` 版本是 `1.2.0`  或者是更高。
> * 确认初始化参数中有添加 `region: 'cn'`，比如：
> 
> ```ts
> const viewer = new XMindEmbedViewer({
>   el: '#container-or-iframe-selector',
>   region: 'cn'
> })
> ```
> 
> 如果上述操作无法解决问题，为了进一步排查原因，请打开 [demo](https://xmindltd.github.io/xmind-embed-viewer/) 并使用页面内 “切换到国内源” 的选项检查速度是否有变快。
> 
> * 假如速度变快了，那么一定是用法有问题，你可以参考 [demo](https://github.com/xmindltd/xmind-embed-viewer/blob/423627eb87f24c72aa68f20e961c9f12d4e7d021/public/index.html#L51) 重新调整你的代码
> * 假如仍然加载慢，很可能是网络运营商线路的问题，awschina cloudfront cdn 节点可能没能覆盖到你的区域或者运营商，这点我们没有办法解决。

我的感觉是，如果暴力一些，我下载了所有的资源文件，直接本地代理都解决了，不过你们目前的方案应该能解决大部分的场景了，感谢了。
